version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flights-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload